# Generated by Django 3.2 on 2021-05-24 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inital_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True)),
                ('published_year', models.IntegerField()),
                ('launch_attempts', models.IntegerField()),
                ('launch_successes', models.IntegerField(default=0)),
                ('launch_consecutive_successes', models.IntegerField(default=0)),
                ('last_failure', models.DateField(blank=True)),
                ('reliability_estimate_lewis_point', models.FloatField(default=0.0)),
                ('reliability_estimate_adjusted_wald_ci_start', models.FloatField(default=0.0)),
                ('reliability_estimate_adjusted_wald_ci_end', models.FloatField(default=0.0)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spacetrends.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleFlightSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('launch_attempts', models.IntegerField(default=0)),
                ('launch_fails', models.IntegerField(default=0)),
                ('leo_attempts', models.IntegerField(default=0)),
                ('leo_fails', models.IntegerField(default=0)),
                ('beyond_leo_attempts', models.IntegerField(default=0)),
                ('beyond_leo_fails', models.IntegerField(default=0)),
                ('deep_space_attempts', models.IntegerField(default=0)),
                ('deep_space_fails', models.IntegerField(default=0)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spacetrends.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('launch_attempts', models.IntegerField(default=0)),
                ('launch_fails', models.IntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spacetrends.site')),
            ],
        ),
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_date', models.DateField()),
                ('launch_id', models.CharField(max_length=255)),
                ('payload', models.CharField(max_length=255)),
                ('mass', models.FloatField(default=0, help_text='Mass in tons')),
                ('site_pad_code', models.CharField(blank=True, help_text='Optional launch site pad code', max_length=255)),
                ('notes', models.TextField()),
                ('orbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spacetrends.orbit')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spacetrends.site')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spacetrends.vehicle')),
            ],
        ),
    ]
