# Generated by Django 3.2.4 on 2021-06-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacetrends', '0002_alter_orbit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
