# Generated by Django 3.2.4 on 2021-06-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacetrends', '0003_auto_20210616_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='orbit_uncertain',
            field=models.BooleanField(default=False, help_text='True when it is unclear whether specified orbit data is accurate.'),
        ),
    ]
